In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Shashwat Bhatt\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Shashwat Bhatt\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Shashwat Bhatt\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Shashwat Bhatt\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Shashwat Bhatt\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:

# Step 1: Importing Pandas and Creating a Dataset

import pandas as pd

In [4]:
# Creating a dataset of popular Indian singers and their achievements
data = {
    'Singer': ['Arijit Singh', 'Shreya Ghoshal', 'Sonu Nigam', 'Lata Mangeshkar', 'Kishore Kumar'],
    'Years_Active': [15, 20, 30, 70, 40],
    'Number_of_Songs': [500, 700, 600, 1000, 800],
    'Awards_Won': [50, 60, 40, 100, 80]
}

# Convert the dictionary into a Pandas DataFrame
singers_df = pd.DataFrame(data)

# Display the dataset
singers_df

            Singer  Years_Active  Number_of_Songs  Awards_Won
0     Arijit Singh            15              500          50
1   Shreya Ghoshal            20              700          60
2       Sonu Nigam            30              600          40
3  Lata Mangeshkar            70             1000         100
4    Kishore Kumar            40              800          80

In [5]:
# Display basic information about the dataset
singers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Singer           5 non-null      object
 1   Years_Active     5 non-null      int64
 2   Number_of_Songs  5 non-null      int64
 3   Awards_Won       5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [8]:
# Show the first few rows of the dataset
singers_df.tail(2)

            Singer  Years_Active  Number_of_Songs  Awards_Won
3  Lata Mangeshkar            70             1000         100
4    Kishore Kumar            40              800          80

In [9]:
# Calculate basic statistical metrics
singers_df.describe()

       Years_Active  Number_of_Songs  Awards_Won
count      5.000000         5.000000    5.000000
mean      35.000000       720.000000   66.000000
std       21.794495       192.353841   24.083189
min       15.000000       500.000000   40.000000
25%       20.000000       600.000000   50.000000
50%       30.000000       700.000000   60.000000
75%       40.000000       800.000000   80.000000
max       70.000000      1000.000000  100.000000

In [10]:

# Calculate specific statistics
max_songs = singers_df['Number_of_Songs'].max()
min_songs = singers_df['Number_of_Songs'].min()
mean_awards = singers_df['Awards_Won'].mean()
median_years = singers_df['Years_Active'].median()

print(f"Maximum number of songs: {max_songs}")
print(f"Minimum number of songs: {min_songs}")
print(f"Average awards won: {mean_awards:.2f}")
print(f"Median years active: {median_years}")

Maximum number of songs: 1000
Minimum number of songs: 500
Average awards won: 66.00
Median years active: 30.0

In [11]:
# Sort singers by the number of songs
sorted_singers = singers_df.sort_values(by='Awards_Won', ascending=False)
sorted_singers

            Singer  Years_Active  Number_of_Songs  Awards_Won
3  Lata Mangeshkar            70             1000         100
4    Kishore Kumar            40              800          80
1   Shreya Ghoshal            20              700          60
0     Arijit Singh            15              500          50
2       Sonu Nigam            30              600          40

In [12]:
# Filter singers who have won more than 50 awards
singers_with_many_awards = singers_df[singers_df['Awards_Won'] > 50]
singers_with_many_awards

            Singer  Years_Active  Number_of_Songs  Awards_Won
1   Shreya Ghoshal            20              700          60
3  Lata Mangeshkar            70             1000         100
4    Kishore Kumar            40              800          80

In [ ]:
import matplotlib.pyplot as plt

# Bar chart of the number of songs by each singer
plt.figure(figsize=(8, 5))
plt.bar(singers_df['Singer'], singers_df['Number_of_Songs'], color='lightblue')
plt.title('Number of Songs by Indian Singers')
plt.xlabel('Singer')
plt.ylabel('Number of Songs')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()